import {test,expect} from '@playwright/test';
import {Match} from '../../dist/match.mjs';
import {control} from './ui-controls.js';
const base=()=>{const g=new Match().g;g.b.fill(null);g.b[80]={t:'K',s:0,p:false};g.b[0]={t:'K',s:1,p:false};return g;};
async function load(page,g){await page.addInitScript(()=>{localStorage.setItem('aether-stage','yankee');localStorage.setItem('aether-war-presentation-v1',JSON.stringify({analysis:false}));});await page.goto('/?debug');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.evaluate(g=>{localStorage.setItem('aether-shogi-v1',JSON.stringify({stage:'yankee',g,past:[],records:[],end:''}));localStorage.setItem('aether-presentation-v1',JSON.stringify({effects:false,tempo:'normal'}));},g);await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');}
async function cell(page,i){const p=await page.evaluate(i=>window.__aether.projectCell(i),i);await page.mouse.click(p.x,p.y);}
test('Yankee promotion, localized log, undo, check and AI acknowledgement',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const g=base();g.b[31]={t:'R',s:0,p:false};await load(page,g);await cell(page,31);await cell(page,22);await page.locator('#yes').click();await expect(page.locator('.war-kanji')).toHaveText('本気');await expect(page.locator('.war-subtitle')).toContainText('ナメんなよ');await expect(page.locator('#war-log')).toContainText('本気');await expect(page.locator('.war-mark')).not.toHaveText('龍');
 await control(page,'#language','selectOption','en');await expect(page.locator('.war-kanji')).toHaveText('本気');await expect(page.locator('.war-subtitle')).toHaveAttribute('lang','en');await expect(page.locator('.war-subtitle')).toContainText('No more messing around');await control(page,'#undo','click');await expect(page.locator('.war-banner')).toHaveCount(0);
 const check=base();check.b[40]={t:'R',s:0,p:false};await load(page,check);await control(page,'#language','selectOption','ja');await cell(page,40);await cell(page,36);await expect(page.locator('.war-kanji')).toHaveText('王手');await expect(page.locator('.war-subtitle')).toContainText('出てこいや');await page.screenshot({path:'test-results/yankee-check.png'});
 await load(page,new Match().g);await control(page,'#ai-toggle-0','click');await expect(page.locator('#war-presentation .war-kanji')).toHaveText('夜露死苦');await control(page,'#ai-toggle-0','click');await expect(page.locator('[data-event="95"].war-banner')).toHaveCount(0);expect(errors).toEqual([]);
});
test('all theme cards render in mobile; missing themed audio never plays samurai audio',async({page})=>{
 await page.setViewportSize({width:390,height:844});await load(page,new Match().g);
 const result=await page.evaluate(async()=>{const {PresentationView}=await import('/presentation-view.js');const {event,IMPLEMENTED}=await import('/battle-events.mjs');let plays=0;const v=new PresentationView({world:document.querySelector('#world'),audioFactory:()=>{plays++;throw Error('unexpected audio');}});await v.ready;v.sources={'17':{'0':{ja:'/audio/samurai.mp3'}}};const issues=[];for(const id of IMPLEMENTED){v.show(event(id,{side:0},{targetCells:[],control:id>=95}),{mode:'subtle',english:true,subtitles:true,canVoice:true,volume:.7});const card=v.current;const dom=v.layer.firstElementChild??document.querySelector('.war-command');if(!card.ja||!card.subtitle)issues.push(id);if(dom&&dom.scrollWidth>dom.clientWidth+2)issues.push('overflow '+id);}v.destroy();return {plays,issues};});expect(result).toEqual({plays:0,issues:[]});
});
